Solution to Week1 Task
CottaCush/Dufuna pull request #12
Opened 2018-06-10 03:06 UTC by Umaynah

THIS IS A PULL REQUEST TEMPLATE! This helps you complete a pull request. Please follow the instructions below. 

## Description
Tell us about your pull request!

**Please make sure your submission is in the correct directory**. In most cases, this is in submissions/YOUR-GITHUB-USERNAME/Week-Number/filename.

For example, if @codedentwickler is completing Week 1:
- I solved the Week 1 task.
- I create a new file inside submissions/codedentwickler/Week1/
- I name this file fizzbuzz.py, hence we have the fizzbuzz solution in submissions/codedentwickler/Week1/fizzbuzz.py

2018-06-10 03:10 UTC, Umaynah commented
I created the sub-folder "Week1"
I uploaded my solution to the FizzBuzz test into the Week1 sub-folder
I also have a new file "about me.md" where you can get to know me.

2018-06-10 13:18 UTC, codedentwickler requested changes
Minor comments to attend to.

2018-06-10 13:18 UTC, codedentwickler commented on submissions/Umaynah/Week1/Fizzbuzz.py
> +
Nice solution.

2018-06-10 13:18 UTC, codedentwickler commented on submissions/Umaynah/about.md
> +
Kindly remove unnecessary lines. One line seems to be enough

2018-06-11 02:20 UTC, Umaynah commented
Edited.

2018-06-11 02:21 UTC, Umaynah commented on submissions/Umaynah/Week1/Fizzbuzz.py
> +
Thanks for the review

2018-06-11 08:04 UTC, codedentwickler approved these changes

2018-06-11 08:04 UTC, merged