pull request
CottaCush/Dufuna pull request #25
Opened 2018-06-13 11:29 UTC by infinidoko

THIS IS A PULL REQUEST TEMPLATE! This helps you complete a pull request. Please follow the instructions below. 

## Description
Tell us about your pull request!

**Please make sure your submission is in the correct directory**. In most cases, this is in submissions/YOUR-GITHUB-USERNAME/Week-Number/filename.

For example, if @codedentwickler is completing Week 1:
- I solved the Week 1 task.
- I create a new file inside submissions/codedentwickler/Week1/
- I name this file fizzbuzz.py, hence we have the fizzbuzz solution in submissions/codedentwickler/Week1/fizzbuzz.py

2018-06-13 11:31 UTC, infinidoko commented
I solved the Week 1 task.
    I created two new files inside submissions/infinidoko/Week1/
    the first file is named aboutme.md and  the other is fizzbuzz.cpp

2018-06-13 15:13 UTC, codedentwickler requested changes

2018-06-13 15:13 UTC, codedentwickler commented on infinidoko/week1/fizzbuzz.txt
> +
Kindly delete this file and update you Pull request. It is a duplicate of what is in `fizzbuzz.cpp`

2018-06-16 23:21 UTC, infinidoko commented
I've made the required changes

2018-06-16 23:33 UTC, merged